name: 'General ci'

description: 'General ci'
runs:
  using: "composite"
  steps:
#    - name: Checkout code
    #      uses: actions/checkout@v2
    #      with:
    #        fetch-depth: 0
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: Build - Clean Jacoco Verify
      shell: bash
      run: >
        mvn --batch-mode --update-snapshots
        clean
        org.jacoco:jacoco-maven-plugin:prepare-agent
        verify
        org.jacoco:jacoco-maven-plugin:report
    - name: Sonar Analyze
      shell: bash
      run: >
        mvn --batch-mode
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.organization=europeana
        -Dsonar.projectKey=europeana_metis-sandbox
        sonar:sonar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}