version: '3.8'

# Container will create database and execute scripts.
# On re-starts it will contain data(and not execute scripts) but on re-builds it will not.
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=sandbox_local
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/database/schema_problem_patterns.sql:/docker-entrypoint-initdb.d/schema_problem_patterns.sql
  rabbitmq:
    image: rabbitmq:3.9.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'