<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>eu.europeana.metis</groupId>
  <artifactId>metis-sandbox</artifactId>
  <version>12-SNAPSHOT</version>
  <packaging>pom</packaging>

  <modules>
    <module>metis-sandbox-common</module>
    <module>metis-sandbox-service</module>
    <module>metis-sandbox-rest</module>
  </modules>

  <scm>
    <url>https://github.com/europeana/metis-sandbox</url>
    <connection>scm:git:https://github.com/europeana/metis-sandbox</connection>
    <developerConnection>scm:git:https://github.com/europeana/metis-sandbox</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.release>21</maven.compiler.release>

    <!--Plugins-->
    <version.maven.compiler.plugin>3.14.0</version.maven.compiler.plugin>
    <version.surefire.plugin>3.5.3</version.surefire.plugin>
    <version.failsafe.plugin>3.5.3</version.failsafe.plugin>
    <version.maven.release.plugin>2.5.3</version.maven.release.plugin>

    <!--Internal-->
    <version.metis>18-SNAPSHOT</version.metis>
    <version.metis-common>20-SNAPSHOT</version.metis-common>
    <version.metis-normalization>18-SNAPSHOT</version.metis-normalization>
    <version.corelib>2.17.8-SNAPSHOT</version.corelib>

    <!--External-->
    <version.spring.boot>4.0.4</version.spring.boot>
    <version.springdoc-openapi-starter-webmvc-api>2.8.6</version.springdoc-openapi-starter-webmvc-api>
    <version.aws.s3>1.12.797</version.aws.s3>
    <version.git-commit-id-plugin>4.0.4</version.git-commit-id-plugin>
    <version.logcaptor>2.7.8</version.logcaptor>
    <version.wiremock>3.13.1</version.wiremock>
    <version.commons.collections4>4.4</version.commons.collections4>
    <version.commons.compress>1.28.0</version.commons.compress>
    <version.commons.io>2.20.0</version.commons.io>
    <version.stax2-api>4.2.1</version.stax2-api>
    <version.woodstox-core>6.4.0</version.woodstox-core>
    <version.elastic.apm>1.55.0</version.elastic.apm>
    <version.bucket4j>8.10.1</version.bucket4j>
    <version.guava>32.1.3-jre</version.guava>
    <version.morphia>2.5.0</version.morphia>
    <version.jetbrains.annotations>24.0.1</version.jetbrains.annotations>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${version.spring.boot}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <!--Release repositories-->
    <repository>
      <id>libs-release</id>
      <name>libs-release</name>
      <url>https://artifactory-prod.eanadev.org/artifactory/libs-release</url>
      <releases>
        <enabled>true</enabled>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
    </repository>
    <!--Snapshot repositories-->
    <repository>
      <id>libs-snapshot</id>
      <name>libs-snapshots</name>
      <url>https://artifactory-prod.eanadev.org/artifactory/libs-snapshot</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </repository>
  </repositories>

  <distributionManagement>
    <repository>
      <id>artifactory-prod.eanadev.org</id>
      <name>artifactory-prod.eanadev.org-releases</name>
      <url>https://artifactory-prod.eanadev.org/artifactory/libs-release-local</url>
    </repository>
    <snapshotRepository>
      <id>artifactory-prod.eanadev.org</id>
      <name>artifactory-prod.eanadev.org-snapshots</name>
      <url>https://artifactory-prod.eanadev.org/artifactory/libs-snapshot-local</url>
    </snapshotRepository>
  </distributionManagement>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${version.maven.compiler.plugin}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${version.surefire.plugin}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${version.failsafe.plugin}</version>
          <configuration>
            <failIfNoTests>false</failIfNoTests>
            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
          </configuration>
          <executions>
            <execution>
              <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-release-plugin</artifactId>
          <version>${version.maven.release.plugin}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

</project>
