info:
  app:
    title: &name Metis Sandbox
    description: Sandbox to process Datasets
    version: 1.0.0
    repository: https://github.com/europeana/metis-sandbox

spring:
  profiles:
    active: default
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
      - org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration
  application:
    name: *name
  servlet:
    multipart:
      max-file-size: 5MB
  rabbitmq:
    virtual-host: sandbox-develop
    host: localhost
    port: 5672
    username: sandbox
    password: sandbox
    ssl:
      enabled:
      algorithm:
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

# spring boot actuator see documentation at
# https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: ["health", "info", "loggers", "metrics", "mappings", "scheduledtasks"]

  endpoint:
    health: # Shows application health information.
      enabled: true

    info: # Displays arbitrary application info.
      enabled: true

    loggers: # Shows and modifies the configuration of loggers in the application.
      enabled: true

    metrics: # Shows ‘metrics’ information for the current application.
      enabled: true

    mappings: # Displays a collated list of all @RequestMapping paths.
      enabled: true

    scheduledtasks: # Displays the scheduled tasks in your application.
      enabled: true

sandbox:
  cors:
    mapping: '*'
  truststore:
    path:
    password:
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/sandbox
    driverClassName: org.postgresql.Driver
    username: sandbox
    password:
    maximumPoolSize: 10           # this is the default we make it explicit in the config.
    leakDetectionThreshold: 5000  # five second should be enough
  dataset:
    clean:
      frequency: 0 0 0 * * ? # At 00:00:00am every day
      days-to-preserve: 7
    max-size: 1000
    creation:
      threads:
        core-pool-size: 10
        max-pool-size: 40
        thread-prefix: sandbox-
  validation:
    edm-sorter-url: http://ftp.eanadev.org/schema_zips/edm_sorter.xsl
    executor:
      pool-size: 10
    predefinedSchemas:
      EDM-INTERNAL:
        url:
        rootLocation:
        schematronLocation:
      EDM-EXTERNAL:
        url:
        rootLocation:
        schematronLocation:
  transformation:
    xslt-url:
  enrichment:
    dereference-url:
    enrichment-url:
  publish:
    mongo:
      application-name:
      db:
      hosts:
      ports:
      authentication-db:
      username:
      password:
      ssl-enable:
    solr:
      hosts:
      zookeeper:
        hosts:
        ports:
        chroot:
        default:
          collection:
        timeout:
  s3:
    access-key:
    secret-key:
    endpoint:
    signing-region:
    thumbnails-bucket:
  portal:
    publish:
      dataset-base-url:
      record-base-url:
  rabbitmq:
    routing-key:
      closed: sandbox.record.closed
    exchange:
      name: sandbox
      dlq: ${sandbox.rabbitmq.exchange.name}.dlq
    queues:
      record:
        log:
          queue: sandbox.record.log
          dlq: ${sandbox.rabbitmq.queues.record.log.queue}.dlq
          routing-key: sandbox.record.#
          auto-start: true
          consumers: 2
          max-consumers: 2
        created:
          queue: sandbox.record.created
          dlq: ${sandbox.rabbitmq.queues.record.created.queue}.dlq
          auto-start: true
        transformation:
          edm:
            external:
              queue: sandbox.record.transformation.edm.external
              dlq: ${sandbox.rabbitmq.queues.record.transformation.edm.external.queue}.dlq
              auto-start: true
        ordered:
          queue: sandbox.record.ordered
          dlq: ${sandbox.rabbitmq.queues.record.ordered.queue}.dlq
          auto-start: true
        validated:
          external:
            queue: sandbox.record.validated.external
            dlq: ${sandbox.rabbitmq.queues.record.validated.external.queue}.dlq
            auto-start: true
          internal:
            queue: sandbox.record.validated.internal
            dlq: ${sandbox.rabbitmq.queues.record.validated.internal.queue}.dlq
            auto-start: true
        transformed:
          queue: sandbox.record.transformed
          dlq: ${sandbox.rabbitmq.queues.record.transformed.queue}.dlq
          auto-start: true
        normalized:
          queue: sandbox.record.normalized
          dlq: ${sandbox.rabbitmq.queues.record.normalized.queue}.dlq
          auto-start: true
        enriched:
          queue: sandbox.record.enriched
          dlq: ${sandbox.rabbitmq.queues.record.enriched.queue}.dlq
          auto-start: true
        media:
          queue: sandbox.record.media.processed
          dlq: ${sandbox.rabbitmq.queues.record.media.queue}.dlq
          auto-start: true
        published:
          queue: sandbox.record.published
          dlq: ${sandbox.rabbitmq.queues.record.published.queue}.dlq
          auto-start: true
