# Spring Actuator Info App
info:
  app:
    title: &appTitle Metis Sandbox
    description: Metis Sandbox to process Datasets
    version: 1.0.0
    repository: https://github.com/europeana/metis-sandbox
    contact:
      name: Europeana Foundation
      email: info@europeana.eu
      url: www.europeana.eu
# Spring Actuator Management (https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/)
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: ["health", "info", "loggers", "metrics", "scheduledtasks", "beans"]
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    scheduledtasks:
      enabled: true
    beans:
      enabled: true
  ## Enables info.app properties
  info:
    env:
      enabled: true

# Truststore
truststore:
  path: /data/certificates/custom-truststore.jks
  password: AsRgzVh3JXRTKE0fTB02Nkbo

# Elastic APM
elastic:
  apm:
    enabled: true
    recording: true
    instrument: true
    service_name: metis-sandbox-rest-local
    server_url: http://localhost:8200
    environment: local
    application_packages: org.europeana,eu.europeana.metis.sandbox
    log_level: ERROR
    capture_body: all
    capture_headers: true
    metrics_interval: 5s

# Spring
spring:
  application:
    name: *appTitle
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:7080/realms/europeana/protocol/openid-connect/certs
  ## Spring Data
  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/sandbox
    driverClassName: org.postgresql.Driver
    username: sandbox
    password:
    maximumPoolSize: 10           # this is the default we make it explicit in the config.
    leakDetectionThreshold: 5000  # five second should be enough
  rabbitmq:
    virtual-host: sandbox-local
    host: localhost
    #Https port for management UI 8081
    port: 5672
    username: sandbox
    password: sandbox
    ssl:
      enabled: false
      algorithm: TLSv1.2
      trust-store:
      trust-store-password:
    listener:
      simple:
        concurrency: 2
        max-concurrency: 2
        prefetch: 1
        retry:
          enabled: true
          initial-interval: 1000ms
          multiplier: 2
          max-attempts: 3
  jpa:
    open-in-view: false

# Metis Sandbox
sandbox:
  cors:
    mapping: '*'
  rate-limit:
    bandwidth:
      capacity:
      time: # in seconds
  debias:
    url:
    connectTimeout: 300
    requestTimeout: 300
  dataset:
    clean:
      frequency: 0 0 0 * * ? # At 00:00:00am every day
      days-to-preserve: 7
    max-size: 1000
    creation:
      threads:
        core-pool-size: 10
        max-pool-size: 40
        thread-prefix: sandbox-
  metrics:
    frequency: '*/30 * * * * *' # every half a minute.
  validation:
    edm-sorter-url: http://ftp.eanadev.org/schema_zips/edm_sorter.xsl
    executor:
      pool-size: 10
    predefinedSchemas:
      EDM-INTERNAL:
        url:
        rootLocation:
        schematronLocation:
      EDM-EXTERNAL:
        url:
        rootLocation:
        schematronLocation:
  transformation:
    xslt-url:
    xslt-update-frequency: 0 0 * * * * # 0 0 * * * * = every hour of every day
  enrichment:
    dereference-url:
    enrichment-properties:
      entity-management-url:
      entity-api-url:
      entity-api-key:
      entity-api-token-endpoint:
      entity-api-grant-params:
  publish:
    mongo:
      application-name: metis-sandbox-local
      db:
      hosts:
      ports:
    solr:
      hosts:
      zookeeper:
        hosts:
        ports:
        chroot:
        default:
          collection:
        timeout: 10
  s3:
    access-key:
    secret-key:
    endpoint:
    signing-region:
    thumbnails-bucket:
  portal:
    publish:
      dataset-base-url:
      record-base-url:
  rabbitmq:
    routing-key:
      closed: sandbox.record.closed
    exchange:
      name: sandbox
      dlq: ${sandbox.rabbitmq.exchange.name}.dlq
    queues:
      record:
        log:
          queue: sandbox.record.log
          dlq: ${sandbox.rabbitmq.queues.record.log.queue}.dlq
          routing-key: sandbox.record.#
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        created:
          queue: sandbox.record.created
          dlq: ${sandbox.rabbitmq.queues.record.created.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        transformation:
          edm:
            external:
              queue: sandbox.record.transformation.edm.external
              dlq: ${sandbox.rabbitmq.queues.record.transformation.edm.external.queue}.dlq
              auto-start: true
              concurrency: 2
              max-concurrency: 2
              prefetch: 1
        validated:
          external:
            queue: sandbox.record.validated.external
            dlq: ${sandbox.rabbitmq.queues.record.validated.external.queue}.dlq
            auto-start: true
            concurrency: 2
            max-concurrency: 2
            prefetch: 1
          internal:
            queue: sandbox.record.validated.internal
            dlq: ${sandbox.rabbitmq.queues.record.validated.internal.queue}.dlq
            auto-start: true
            concurrency: 2
            max-concurrency: 2
            prefetch: 1
        transformed:
          queue: sandbox.record.transformed
          dlq: ${sandbox.rabbitmq.queues.record.transformed.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        normalized:
          queue: sandbox.record.normalized
          dlq: ${sandbox.rabbitmq.queues.record.normalized.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        enriched:
          queue: sandbox.record.enriched
          dlq: ${sandbox.rabbitmq.queues.record.enriched.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        media:
          queue: sandbox.record.media.processed
          dlq: ${sandbox.rabbitmq.queues.record.media.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        published:
          queue: sandbox.record.published
          dlq: ${sandbox.rabbitmq.queues.record.published.queue}.dlq
          auto-start: true
          concurrency: 2
          max-concurrency: 2
          prefetch: 1
        debias:
          ready:
            queue: sandbox.record.debias.ready
            dlq: ${sandbox.rabbitmq.queues.record.debias.ready.queue}.dlq
            auto-start: true
            concurrency: 2
            max-concurrency: 2
            prefetch: 20
            batch-size: 20
