BEGIN;
DROP TABLE IF EXISTS dataset_log;
DROP TABLE IF EXISTS dataset;
DROP TABLE IF EXISTS record_log;
DROP TABLE IF EXISTS record_error_log;
DROP TABLE IF EXISTS record;
DROP TABLE IF EXISTS thumbnail;
DROP TABLE IF EXISTS default_transform_xslt;
COMMIT;
