DROP SCHEMA IF EXISTS public CASCADE;
DROP SCHEMA IF EXISTS engine_record CASCADE;
DROP SCHEMA IF EXISTS problem_patterns CASCADE;
DROP SCHEMA IF EXISTS integration CASCADE;
DROP SCHEMA IF EXISTS rate_limit CASCADE;
