drop table if exists dataset;
drop table if exists record_log;

create table dataset
(
    dataset_id varchar(255) generated by default as identity,
    dataset_name varchar(255),
    records_quantity integer,
    created_date timestamp default now(),
    primary key (dataset_id)
);

create table record_log
(
    dataset_id varchar(100) not null,
    id varchar(100) not null,
    step varchar(30) not null,
    content VARCHAR(MAX),
    error VARCHAR(MAX),
    stack_trace VARCHAR(MAX),
    result varchar(30),
    primary key (dataset_id, id, step)
)