drop table if exists dataset;
drop table if exists record_log;
drop table if exists record_error_log;
drop table if exists thumbnail;

create table if not exists dataset (
   dataset_id int generated by default as identity,
   dataset_name varchar(255) not null,
   records_quantity integer not null,
   created_date timestamp with time zone default now(),
   country varchar(35),
   language varchar(3),
   record_limit_exceeded bool,
   xslt_edm_external_content text,
   Primary Key (dataset_id)
);

create table  if not exists record_log (
   id int generated by default as identity,
   record_id varchar(100),
   dataset_id int not null,
   step varchar(30) not null,
   status varchar(30) not null,
   content text not null,
   created_date timestamp with time zone default now(),
   Primary Key(id),
   Unique (record_id, dataset_id, step)
);

create table if not exists record_error_log (
    id int generated by default as identity,
    record_id varchar(100) not null,
    dataset_id int not null ,
    step varchar(30) not null,
    status varchar(30) not null,
    message text not null ,
    stack_trace text not null ,
    created_date timestamp with time zone default now(),
    Primary Key (id)
);

create table if not exists thumbnail (
    id int generated by default as identity,
    dataset_id varchar(100) not null ,
    thumbnail_id varchar(200) not null,
    Primary Key (id),
    unique (dataset_id, thumbnail_id)
);
