name: CI

on:
  push:
    #Do not run on main to avoid duplicate builds during release
    branches-ignore:
      - '!master'
      - '!main'
    #Run on release tags
    tags:
      - 'v*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install media software
        uses: europeana/metis-actions/actions/media-software-install-steps@main
      - name: Build code and Sonar Analyze
        uses: europeana/metis-actions/actions/build-analyze@main
        with:
          sonar_organization: europeana
          sonar_project_key: europeana_metis-sandbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
