name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Install media software
        uses: europeana/metis-actions/actions/media-software-install-steps@main
      - name: CI steps
        uses: europeana/metis-actions/actions/build-analyze@main
        with:
          sonar_organization: europeana
          sonar_project_key: europeana_metis-sandbox
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sonar_token: ${{ secrets.SONAR_TOKEN }}
