name: performance

on:
  workflow_dispatch:
    branches:
      - feat/*
      - develop
    inputs:
      users:
        description: 'Amount of users (threads)'
        required: true
        default: 1
      rampUp:
        description: 'Ramp up period (in seconds)'
        required: true
        default: 5
      loopCount:
        description: 'Amount of runs'
        required: true
        default: 1
      scenario:
        type: choice
        description: 'Scenario to run'
        required: true
        options:
          - scenario-1-harvest-file
          - scenario-2-harvest-oaipmh
          - scenario-3-harvest-file-and-oaipmh
jobs:
  performance-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        run: |
          sudo add-apt-repository ppa:openjdk-r/ppa -y
          sudo apt-get update -y
          sudo apt install openjdk-11-jdk -y
      - name: Set up jmeter 5.5
        run: |
          java -version
          wget https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.5.zip
          unzip apache-jmeter-5.5.zip
          pwd
          cd apache-jmeter-5.5/bin
          ./jmeter -v
          pwd
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: scenario
        run: |          
          uuid_arr=(`echo $(cat /proc/sys/kernel/random/uuid | tr '-' ' ')`)
          scenario=$GITHUB_WORKSPACE'/'src/main/resources/performance/${{ github.event.inputs.scenario }}'.jmx'
          echo $scenario
          echo $uuid_arr
          cat $scenario
